force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <label>Bus Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Last_Ping_Location__c.field-meta.xml
<CustomField>
    <fullName>Last_Ping_Location__c</fullName>
    <label>Last Ping Location</label>
    <scale>6</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Next_Service_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Next_Service_Odometer_Reading__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Next Service Odometer Reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Garage__c/Garage__c.object-meta.xml
<CustomObject>
    <label>Garage</label>
    <nameField>
        <label>Garage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Garage__c/fields/Location_City__c.field-meta.xml
<CustomField>
    <fullName>Location_City__c</fullName>
    <label>Location City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>Maintenance-{0000}</displayFormat>
        <label>Maintenance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Maintenance</relationshipLabel>
    <relationshipName>BusMaintenance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Garage__c.field-meta.xml
<CustomField>
    <fullName>Garage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garage</label>
    <referenceTo>Garage__c</referenceTo>
    <relationshipLabel>Maintenance</relationshipLabel>
    <relationshipName>GarageMaintenance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Schedule_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date_Time__c</fullName>
    <label>Schedule Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Schedule_Reason__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Reason__c</fullName>
    <label>Schedule Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/BusMaintanenceBatchJobTest.cls
@isTest
public class BusMaintanenceBatchJobTest {

    @testsetup
    static void setup(){
        List<Bus__c> busList = new List<Bus__c>();
        List<Garage__c> garageList = new List<Garage__c>();
        
    	Bus__c testBus1 = new Bus__c(
        	Name = 'Test Bus 1',
            Maximum_Capacity__c = '60',
            Odometer_Reading__c = 10000,
            Year__c = '2000'
        );
        busList.add(testBus1);
        
        Bus__c testBus2 = new Bus__c(
        	Name = 'Test Bus 2',
            Maximum_Capacity__c = '60',
            Odometer_Reading__c = 20000,
            Year__c = '2005'
        );
        busList.add(testBus2);
        
        Bus__c testBus3 = new Bus__c(
        	Name = 'Test Bus 3',
            Maximum_Capacity__c = '60',
            Odometer_Reading__c = 30000,
            Year__c = '2010'
        );
        busList.add(testBus3);
        
        Garage__c testGarage1 = new Garage__c(
            Location_City__c = 'San Diego',
            Location__Latitude__s = 32.7157,
       		Location__Longitude__s = 117.1611
        );
        garageList.add(testGarage1);
        
        Garage__c testGarage2 = new Garage__c(
            Location_City__c = 'LA',
            Location__Latitude__s = 34.0522,
            Location__Longitude__s = 118.2437
        );
        garageList.add(testGarage2);
        
        Garage__c testGarage3 = new Garage__c(
            Location_City__c = 'New York',
            Location__Latitude__s = 40.7128,
            Location__Longitude__s = 74.0060
        );
        garageList.add(testGarage3);
        
        insert busList;
        insert garageList;
    }
    
    @isTest
    static void testServiceRequired(){
        List<Bus__c> busList = [SELECT Id, Name, Last_Ping_Location__Latitude__s,Last_Ping_Location__Longitude__s,
                          	     	   Next_Service_Odometer_Reading__c
            			  		FROM Bus__c
                         	   ];
        for(Bus__c bus : busList){
            if(bus.Name == 'Test Bus 1'){
        		bus.Odometer_Reading__c = 15100;
        		bus.Last_Ping_Location__Latitude__s = 33.1192;
        		bus.Last_Ping_Location__Longitude__s = 117.0864;    
            }
            if(bus.Name == 'Test Bus 2'){
        		bus.Odometer_Reading__c = 26000;
        		bus.Last_Ping_Location__Latitude__s = 34.28056;
        		bus.Last_Ping_Location__Longitude__s = 119.2945;
            }
            if(bus.Name == 'Test Bus 3'){
        		bus.Odometer_Reading__c = 35550;
        		bus.Last_Ping_Location__Latitude__s = 40.7357;
        		bus.Last_Ping_Location__Longitude__s = 74.1724;
            }
        }
        update busList;
        
        Test.startTest();
        Database.executeBatch(new BusMaintanenceBatchJob());
        Test.stopTest();
        
        List<Maintenance__c> maintenanceList = [SELECT Id, Bus__c, Schedule_Date_Time__c, 
                                                       Schedule_Reason__c, Garage__c
                                                FROM Maintenance__c];
        
        Bus__c updatedBus = [SELECT Next_Service_Odometer_Reading__c, Last_Ping_Location__c FROM Bus__c WHERE Name = 'Test Bus 1']; 
        
        System.assertEquals(3, maintenanceList.size());
        System.assertEquals(20000, updatedBus.Next_Service_Odometer_Reading__c);
		System.assertEquals([SELECT Id FROM Garage__c WHERE Location_City__c = 'San Diego'].Id, [SELECT Id, Garage__c FROM Maintenance__c WHERE Bus__c =: updatedBus.Id].Garage__c);
    }
}